### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by mcepl** [supermihi/pytaglib#13]
When running pyprinttags on http://mcepl.fedorapeople.org/tmp/12%20Tob%C4%9B%20se%20zal%C3%ADbilo.ogg I get:
```
$ pyprinttags *.ogg
Traceback (most recent call last):
  File "/home/matej/.local/bin/pyprinttags", line 9, in <module>
    load_entry_point('pytaglib==1.0.3', 'console_scripts', 'pyprinttags')()
  File "/home/matej/.local/lib/python2.7/site-packages/pyprinttags.py", line 28, in script
    line = "TAGS OF '{0}'".format(os.path.basename(filename))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 6: ordinal not in range(128)
$
```
Using `taglib-1.8-7.20130218git.el7.x86_64` on RHEL-7 with `pytaglib-1.0.3.tar.gz`

**Comment by mcepl** [comment]
Works, perfect! Thank you
