### ISSUE TITLE
1.4.5: pyprinttags.py installation

### ISSUE THREAD

**Issue by pgajdos** [supermihi/pytaglib#62]
Hi,

`pyprinttags.py` does not get installed wity `python setup.py install`, leaving pyprinttags disfunctional for me. Installing `pyprinttags.py` manually into python3 sitelib dir fixes the issue.

For what is worth, build log of the build is here:
https://build.opensuse.org/public/build/home:pgajdos/openSUSE_Tumbleweed/x86_64/python-pytaglib/_log

Do I something wrong?

**Comment by supermihi** [comment]
Hm, `setup.py install` does install the script on my installation. Note that it is called `pyprinttags3` if you are running python3.

Can you also try the latest `master`? I have removed a line in setup.py that was responsible for the error
> file pyprinttags.py (for module pyprinttags) not found
might have also fixed your problem.

**Comment by pgajdos** [comment]
Yes, pyprinttags script is installed. However, when I run it, I get:
```
Traceback (most recent call last):
  File "/usr/bin/pyprinttags", line 11, in <module>
    load_entry_point('pytaglib==1.4.5', 'console_scripts', 'pyprinttags3')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'pyprinttags'
```
Thus I thought `pyprinttags.py` module is missing from the system. And when it is manually installed:
```
[   96s] + mkdir -p /home/abuild/rpmbuild/BUILDROOT/python-pytaglib-1.4.5-13.1.x86_64/usr/lib/python3.7/site-packages
[   96s] + install -m 644 src/pyprinttags.py /home/abuild/rpmbuild/BUILDROOT/python-pytaglib-1.4.5-13.1.x86_64/usr/lib/python3.7/site-packages
```
`pyprinttags` works again:
```
$ pyprinttags 
usage: pyprinttags [-h] [-b] file [file ...]
pyprinttags: error: the following arguments are required: file
$
```

**Comment by supermihi** [comment]
Under which setting does the installation *not* work? Is it when you use `python setup.py install` or when using some rpm method?

**Comment by LeeiFrankJaw** [comment]
I got the same problem by installing pytaglib via pip.

```
$ pyprinttags3 
Traceback (most recent call last):
  File "/home/pony/.local/bin/pyprinttags3", line 11, in <module>
    load_entry_point('pytaglib==1.4.5', 'console_scripts', 'pyprinttags3')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'pyprinttags'
```

**Comment by supermihi** [comment]
Thanks, I am now able to reproduce the problem. Working on a fix ...
